# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      LDFLAG_PARAM: "-X main.Build=${{ github.ref_name }}"
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: TEST
      uses: wangyoucao577/go-release-action@v1.46
      with:
        ldflags: "-X main.Build=${{ github.ref_name }}"

    - name: Git checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
