name: Release James binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux]
        goarch: [amd64,arm64]
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Get latest tag
        run: LATEST_TAG=$(git describe --tags)

      - name: Build release
        uses: wangyoucao577/go-release-action@v1.46
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "."
          binary_name: "james"
          extra_files: LICENSE README.md
          sha256sum: true
          ldflags: "-X main.Build=$LATEST_TAG"
